### ISSUE TITLE
Reflect search query in URL

### ISSUE THREAD

**Issue by stefanjudis** [uetchy/namae#12]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to send around URLs that reflect my search query.

**Describe the solution you'd like**
If I go to https://namae.dev/ and e.g. search for `schnitzel` i'd like the URL to be updated to e.g. https://namae.dev/schnitzel/ or something similar.

**Describe alternatives you've considered**
No alternatives. :) 

**Additional context**
...

Thanks. 🎉

**Comment by uetchy** [comment]
@stefanjudis Thanks for the suggestion! Now you can get a persistent search result like this:

https://namae.dev/s/schnitzel

Depending on the cache status for CDN, it might be delayed to deliver the latest version of the app to your browser.
