### ISSUE TITLE
Feature request: Categorize cards with headers

### ISSUE THREAD

**Issue by Snazzah** [uetchy/namae#161]
### Is your feature request related to a problem? Please describe.

The page when searching a name can get cluttered, with all the services bunched up can get confusing when you just want to find a couple of services.

### Describe the solution you'd like

Group the cards into headers like "Social", "Development", "Serverless Services" for Heroku and such, etc.

### Commitment

Send a pull-request

**Comment by uetchy** [comment]
Love the idea! Can you come up with some groupings for the currently supported cards?

**Comment by Snazzah** [comment]
@uetchy 
Social Brand - Twitter, YouTube, Reddit, GitHub Organization, GitLab, Slack
Domains - Domains, js.org, mod.land
Programming - NPM, PyPi, Rust, RubyGems, Hex, OCaml, Linux
Serverless Services - Netlify, Vercel, Cloudflare Pages, AWS S3, Firebase
Search Results - GitHub Repository, App Store, Google Play Store, Firefox Add-ons

**Comment by uetchy** [comment]
Thanks!

With a bit of reorg, we'd go with this:

Organization: GitHub Organization, GitLab Organization, Slack
Social Network: Twitter, Reddit, YouTube
Web: domains, js.org, mod.land, Fly.io, Heroku, Netlify, Vercel, Cloudflare Pages, AWS S3, Firebase
Package: npm, PyPI, crates.io, RubyGems, Hex.pm, OPAM, Linux
App: App Store, Google Play Store
Web Extension: Firefox Add-ons, Chrome Web Store
Misc: GitHub Repository

**Comment by uetchy** [comment]
Released now
