### ISSUE TITLE
Candidates containing é (accent aigu)

### ISSUE THREAD

**Issue by uneco** [uetchy/namae#17]
**Describe the bug**
When a French-ish name is entered, the suggestions include **é**.
This looks like a bug because a few providers do not support non-ascii characters.

**To Reproduce**
1. Go to namae.dev
2. Input French-ish word. ex. `bonjour`, `mignon`, `bleu`, ...
3. Names like `Déprimantform`, `Alléchantcast` will appear in suggestions.

**Expected behavior**
**è** should be replaced by **e**. (Just as **Hermès**'s domain name is `hermes.com`)

**Screenshots**
<img width="636" alt="スクリーンショット 2020-02-11 17 27 58" src="https://user-images.githubusercontent.com/603523/74221164-cc355580-4cf4-11ea-9be3-6fb2b291693e.png">

**Desktop:**
 - macOS, Chrome

**Comment by uetchy** [comment]
@uneco Thank you for letting me know about that!
I pushed a fixed version of the app. You can test it from now.

**Comment by uneco** [comment]
Thank you! Unregistering the service worker and trying again resolved the issue.
