### ISSUE TITLE
Instagram support

### ISSUE THREAD

**Issue by flawyte** [uetchy/namae#37]
Not sure why it hasn't been added yet? But it'd be cool to check for instagram username availability too.

I might give it a try and submit a PR soon!

**Comment by uetchy** [comment]
It sounds really nice! If you have any problem with integrating Instagram with namae, feel free to ask me on this issue.

**Comment by flawyte** [comment]
The only issue remaining is how to get the right provider name to show? I've edited both japanese and english `translation.json` files but it still won't show up :

![image](https://user-images.githubusercontent.com/1585006/77154960-0c7ab700-6a9d-11ea-9a22-4a7c4f7a325c.png)

I used the code from `TwitterCard` as base so I don't get what I'm missing. Here are the relevant parts :

```tsx
// ...
import {useTranslation} from 'react-i18next';

const InstagramCard: React.FC<{query: string}> = ({query}) => {
  const {t} = useTranslation();

  // ...

  return (
    <Card title={t('providers.instagram')}>
      { /* ... */ }
    </Card>
  );
};
```

`*/translation.json` :

![image](https://user-images.githubusercontent.com/1585006/77155746-48fae280-6a9e-11ea-9978-d3361365f614.png)

**Comment by uetchy** [comment]
Got it. You need to increment the translation version to invalidate the previously cached translation files.

https://github.com/uetchy/namae/blob/61a7d2b9b8670122b585b47996cedf458938430d/web/src/util/i18n.ts#L8

Increment `TRANSLATION_VERSION` to `1.12`.

**Comment by flawyte** [comment]
Done! See [PR](https://github.com/uetchy/namae/pull/38).
